FROM ubuntu:latest

LABEL maintainer="daniel@sukoneck.com"

ARG STEAM_USERNAME
ARG STEAM_PASSWORD
ARG ASSETTO_SERVER_CFG
ARG ASSETTO_ENTRY_LIST

# COPY . /app

RUN set -x \
    # get dependencies
    && apt-get update 
RUN set -x \
    # && apt-get install -y --no-install-recommends --no-install-suggests \
    && apt-get install -y \
		lib32gcc1 \
        libc6-i386 \
        lib32stdc++6 \
        ca-certificates \
        # libcurl4 shooting in the dark
        # xfonts-scalable shooting in the dark
        # libsdl2-2.0-0:i386 couldn't find
        libsdl2-2.0-0 \
        # libc6:i386 couldn't locate
        # libncurses5:i386 couldn't locate
        # libstdc++6:i386 couldn't locate
        # ia32-libs this is decommed
		lib32z1 \
        wget \
        curl \
        # ufw container doesn't need this
        # zlib1g:i386 couldn't locate
        && apt-get clean autoclean \
        && apt-get autoremove -y 
WORKDIR /home/steam
RUN set -x \
    # set up directory and permissions for /home/steam/assetto/
    # && mkdir /home/steam \
    # && chmod -R 755 /home/steam/ \
    # get and prep steamcmd
    # && cd /home/steam \
    # && wget http://media.steampowered.com/client/steamcmd_linux.tar.gz \
    # && tar -xvf steamcmd_linux.tar.gz \
    && wget 'https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz' \
    && tar -xvzf steamcmd_linux.tar.gz \
    && rm -f steamcmd_linux.tar.gz \
    && chmod -R 777 /home/steam/ 
    # configure networking
    # && ufw allow 9600 \
    # && ufw allow 8081 \
    # && ufw enable \
# RUN bash -x /home/steam/steamcmd.sh +login $STEAM_USERNAME $STEAM_PASSWORD
RUN set -x \
    && bash -x /home/steam/steamcmd.sh 
    # configure steam and download assetto server
    # && cd /home/steam \
    # && ./steamcmd.sh 
    # +@sSteamCmdForcePlatformType windows 
        # +login $STEAM_USERNAME $STEAM_PASSWORD \
        # +force_install_dir ./assetto \
        # +app_update 302550 validate \
        # +quit 
WORKDIR /home/steam/assetto/cfg
RUN set -x \
    # configure assetto server
    # && cd /home/steam/assetto/cfg \
    && rm -f /home/steam/assetto/cfg/* \
    && wget $ASSETTO_SERVER_CFG \
    && wget $ASSETTO_ENTRY_LIST \
    && chmod -R 755 /home/steam/ 
    # attach custom tracks/cars
    # && link content to place \
    # configure stracker? depends on zlib1g:i386
    # ???
    # leave in the right directory
    # && cd /home/steam/assetto/
WORKDIR /home/steam
CMD ["./acServer","start"]

# EXPOSE 20100 \
# 	8700 \
# 	27000